version: '3.8'

services:
  postgres:
    container_name: fleetnav_container
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fleetNav
    restart: always

  pgadmin:
          image: dpage/pgadmin4
          restart: always
          environment:
              - PGADMIN_DEFAULT_EMAIL=admin@admin.com
              - PGADMIN_DEFAULT_PASSWORD=admin
          ports:
              - 5050:80