services:
    postgres:
        container_name: pg_container
        image: postgres:16-alpine
        ports:
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: fleetNav
        restart: always

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - 5050:80

    eureka-server:
        container_name: eureka-server
        image: ralexale/fleetnav-eureka-server:0.0.1
        ports:
            - 8761:8761
        restart: always

    config-server:
        container_name: config-server
        image: ralexale/fleetnav-config-server:0.0.1
        ports:
            - 8085:8085
        restart: always
        depends_on:
            - eureka-server

    api-gateway:
        container_name: api-gateway
        image: ralexale/fleetnav-api-gateway:0.0.1
        ports:
            - 8088:8088
        restart: always
        depends_on:
            - eureka-server
            - config-server

    chat-service:
        container_name: chat-service
        image: ralexale/fleetnav-chat-service:0.0.1
        ports:
            - 8083:8083
        restart: always
        depends_on:
            - eureka-server
            - config-server
            - api-gateway

    multitenant-service:
        container_name: multitenant-service
        image: ralexale/fleetnav-multitenant-service:0.0.1
        ports:
            - 8089:8089
        restart: always
        depends_on:
            - eureka-server
            - postgres
            - config-server
            - api-gateway
