version: '1'

services:
  postgres:
    container_name: fleetnav_container
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fleetNav
    restart: always

  pgadmin:
          image: dpage/pgadmin4
          restart: always
          environment:
              - PGADMIN_DEFAULT_EMAIL=admin@admin.com
              - PGADMIN_DEFAULT_PASSWORD=admin
          ports:
              - 5050:80

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "5333:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
