spring:
  application:
    name: FLEETNAV-SERVICE


  datasource:
    # url: jdbc:postgresql://localhost:5433/fleetNav
    # username: postgres
    # password: postgres
    
    url: jdbc:postgresql://localhost:5432/fleetNav
    username: postgres
    password : juanpablo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090
  servlet:
    context-path: /api/v1
