spring:
  application:
    name: FLEETNAV-SERVICE


  datasource:
    url: jdbc:postgresql://localhost:5432/fleetnav
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081